name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   env:
    #     AWS_POOL_ID: ${{ secrets.AWS_POOL_ID }}
    #   run: npm run test

    - name: Build with secrets
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        S3_BASE_URL: ${{ secrets.S3_BASE_URL }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: npm run build

    - name: Copy index.html to 404.html
      run: cp dist/ryan-portfolio-ui/index.html dist/ryan-portfolio-ui/404.html

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/ryan-portfolio-ui
        enable_jekyll: true
