name: GitHub Pages

on:
  push:
    branches:
    - pipeline_update

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm run test

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/lucasbsanders.github.io
        enable_jekyll: true

    - uses: actions/checkout@gh-pages
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "dist/lucasbsanders.github.io/index.html"
        target: "dist/lucasbsanders.github.io/404.html"
